### ISSUE TITLE
CW support

### ISSUE THREAD

**Issue by jfmcbrayer** [jfmcbrayer/brutaldon#20]
Currently CWs are used as titles, and the whole toot is shown. 

The right thing to do for non-JS isn't at all clear. You can hide things behind a full click, but that interrupts the flow of reading the timeline (open full toot, back, continue). Worse in a thread.

For progressively enhanced, the right thing to do is obvious.

**Comment by picsi** [comment]
is hiding with CSS a no-go?

**Comment by jfmcbrayer** [comment]
Basically, no, not before progressive enhancement.

Lynx ignores CSS, so it would have no effect.

And if you hide with CSS, then you have to show with JavaScript. So for progressive enhancement in graphical browsers, that's the way to go, but it doesn't solve the basic problem.

**Comment by jfmcbrayer** [comment]
Apparently the correct thing is to use

```
<details>
        <summary>CW: very silly contents. </summary>
        <p>And now, for something completely different</p>
</details>
```

I have done this. It doesn't fix anything for Lynx, sadly, but it is technically correct and fixes this issue without JavaScript.

**Comment by bhtooefr** [comment]
A couple ideas for a better design:

* Have CW state as a user preference. Some users are OK with having all CWs opened by default (so there's nothing to degrade in that case).
* Have CW state as a per-thread thing. Note that Mastodon in like 2.3 or so added this in its front end, so you can open/close all CWs in a thread. This reduces disruptiveness.
* Store CW state server-side, and make CW open/close point to an anchor on the same page. So, you make a round trip and go through the page load/render phase again, but you end up at the same place as before.

**Comment by jfmcbrayer** [comment]
Thanks for your input. It might be something I work on in a branch.
