### ISSUE TITLE
Multi-account support

### ISSUE THREAD

**Issue by jfmcbrayer** [jfmcbrayer/brutaldon#22]
This would require a Django login and registration for brutaldon. And cross-account actions would require quite a bit of refactoring. But otherwise not hard.

**Comment by jfmcbrayer** [comment]
Minimal support suggested by @enkiv2 is to make it clearer which account you are using (in page title, maybe also in header bar). This is for if you are using your usual browser facilities to multi-account, such as container tabs.

**Comment by enkiv2** [comment]
Awesome, thanks!

**Comment by jfmcbrayer** [comment]
Going to close this, and open a project later when I feel like tackling real multi-account support.
