### ISSUE TITLE
Make toot timestamps humane but not relative

### ISSUE THREAD

**Issue by jfmcbrayer** [jfmcbrayer/brutaldon#28]
The problem with relative timestamps is that they're only accurate on page load, so that's not good.
But we don't want ugly over-detailed timestamps either.

**Comment by oct2pus** [comment]
Maybe just a "Month Day Time, Year timestamp
With an option by server host between 24 and 12 hour times

**Comment by jfmcbrayer** [comment]
Something like that. Maybe no year for things in the current year, no date for things on the current day.

**Comment by jfmcbrayer** [comment]
Done!
