### ISSUE TITLE
`newer` and `older` should go back to the same posts

### ISSUE THREAD

**Issue by raingloom** [jfmcbrayer/brutaldon#30]
Right now when you open `/home` and then click `older` and then click `newer` you get a different list of toots. I think it would be more consistent if clicking `newer` and then `older` was practically a no-op.

Is this possible? Does the API allow this?

**Comment by jfmcbrayer** [comment]
I agree that that's a desirable goal. The straightforward way of using the API doesn't achieve it.

It would be easy-ish to solve this by saving a lot more state and a lot more user information. I don't want to do that if I can avoid it...I'll look into it further.

**Comment by jfmcbrayer** [comment]
Honestly, considering just removing the 'newer' button.

**Comment by jfmcbrayer** [comment]
For now I've removed the 'newer' button. There is an additional API parameter that works correctly in Mastodon 2.6, but that's not generally available yet.

**Comment by jfmcbrayer** [comment]
This very old bug should be fixed by 5c11d3c871b56aab7fb9b36685d2e6d54870676d. Not tested on older versions of Mastodon.
