### ISSUE TITLE
Add setting to hide replies

### ISSUE THREAD

**Issue by nipos** [jfmcbrayer/brutaldon#32]
Pleroma displays all replies to other posts in the timeline.
That fills all timelines with very much nonsense.
I can't use Pleroma correctly in that way.
Mastodon filters replies out by default.
It would be nice if you could add an setting to filter the replies out with Pleroma.
I implemented that function in the last release of Halcyon and it's very easy.
Just check if the in_reply_to_id variable of an post is empty.
If it's empy,display that post and if it isn't,ignore it.
But please note that there are some Pleroma users who like these random posts so that should be an optional setting.

**Comment by jfmcbrayer** [comment]
I've implemented this (and filtering boosts, as well).
