### ISSUE TITLE
Fix compatibility < 2.1.0

### ISSUE THREAD

**Issue by jfmcbrayer** [jfmcbrayer/brutaldon#33]
On older instances the user dict returned by account_verify_credentials does not include the 'source' dict. This leads to a crash after logging in.

Looking for workarounds.

Cc: @halcy

**Comment by halcy** [comment]
For the "note" field, you could strip stuff yourself from the htmlified note in the user dicts. Default values, likely little you can do if you want to _show_ users what's going to happen, but if your API calls do not specify sensitiveness / visibility, the default values should still be respected.

You COULD have an internal "default visibility" or "last used visibility" type setting when a source dict is not available, I guess, but that's more user state to keep around, which is probably bad.

**Comment by jfmcbrayer** [comment]
This is probably not still an issue...
