### ISSUE TITLE
Favourite or Boost Colour Invert

### ISSUE THREAD

**Issue by WuShufei** [jfmcbrayer/brutaldon#37]
In Lynx at least, in FullBrutalism mode, Brutaldon used to invert the colours for "boost" and "favourite" once a toot had been boosted/favourited.  That is, those selectors were highlighted.  Now it no longer does so.  Brutaldon will now say "Favourited" in plain text, but inversion is lost. This makes it harder to see when a toot has been dealt with in this way.

Tank you!

**Comment by jfmcbrayer** [comment]
I'm not sure what markup was previously creating the inverse video text. Possibly \<i\>?  I can check this at some point.

**Comment by jfmcbrayer** [comment]
Fixed in master; will get deployed whenever I package up a release.
