### ISSUE TITLE
When JS is disabled, using the default theme, on mobile, menu covers posting form

### ISSUE THREAD

**Issue by jfmcbrayer** [jfmcbrayer/brutaldon#40]
This is a consequence of adding styling to fix navbar to top: body.has-navbar-fixed-top, nav.is-fixed-top.

The correct behavior without JavaScript is for the menu to be expanded, but not to overlap any other page elements.

The way to achieve this is to leave those classes off of the elements above in the server-generated HTML, then *add them* in on-page-load JavaScript. There is already existing code for manipulating the navbar menu on load, so this is easy to add.

**Comment by jfmcbrayer** [comment]
But on the other hand, this code would break something working fine in desktop.

**Comment by klundry** [comment]
I am getting this issue on Firefox mobile even with javascript enabled.

**Comment by jfmcbrayer** [comment]
I've fixed this and will deploy the fix to brutaldon.online later.
