### ISSUE TITLE
File upload without extension or with non-standard extension fails, Server Error (500)

### ISSUE THREAD

**Issue by bhtooefr** [jfmcbrayer/brutaldon#45]
When uploading a file without a file extension, or with a non-standard extension, Brutaldon gives a 500 error.

Uploading a PNG file named "scrn0,b60" works on Mastodon (and the file is correctly recognized as a PNG), but causes the error on Brutaldon. I encountered this initially on NetSurf 3.8 build 4318 on RISC OS (as RISC OS doesn't natively have file extensions), but I did the testing before submitting this issue on Vivaldi 2.0.1309.37 on Windows 10 1803.

I also attempted experimenting by giving it .png (correct), .jpg (supported by Mastodon but not correct), and .mp3 (a well-known filetype that isn't supported by Mastodon) extensions, and all of these uploads succeeded, and Mastodon's media server stored them as .png files.

A subsequent attempt to use a .jort extension (not well-known) failed with the same server error.

For further information, I was using brutaldon.online as the Brutaldon instance, and mastodon.social as the Mastodon instance.

**Comment by jfmcbrayer** [comment]
Upstream pull request is merged, but you have to use git HEAD rather than a release of Mastodon.py in order to take advantage of it. Brutaldon will automatically use it when Mastodon.py updates in PyPi.
