### ISSUE TITLE
Replying to a toot puts the marker below the quoted user

### ISSUE THREAD

**Issue by Hund** [jfmcbrayer/brutaldon#46]
When I reply to a user the expected behvaiour is to put the marker next to the username with once space like this:

```
@hund |
```

But what happens is this:

```
@hund
|
```

Which means that you have to start every reply with deleting one character. I'm not sure if this is a "feature" or a bug? If it's a feature, please add an option to let the user choose this behaviour themselves.

Thank you! :)

**Comment by jfmcbrayer** [comment]
This was intentional, but I also don't feel strongly about it, so I've removed it.
