### ISSUE TITLE
auto-mentions seem to be broken

### ISSUE THREAD

**Issue by raingloom** [jfmcbrayer/brutaldon#47]
when i replied to a thread, it didn't fill in the mentions it used to, same when i clicked on "mention" on a /user page

there have been similar issues before when editing a reply

**Comment by jfmcbrayer** [comment]
Yes, this is serious, I'll look at it as soon as I can.

**Comment by jfmcbrayer** [comment]
This is fixed in v2.8.1, which I have just pushed.
