### ISSUE TITLE
Jumping back to the post that was faved/boosted, getting rid of confirmations for boosts/faves for JS-less mode

### ISSUE THREAD

**Issue by raingloom** [jfmcbrayer/brutaldon#48]
In JS-less mode, when I fave a post in a thread, it opens a confirmation page and then leads me back to where I came from, except I have to scroll down to the post I was reading in the possibly several screens long thread.
I'm not sure what the feature is called, but websites often let you jump to sections within the page without reloading, using links that end in `#something_like_this`. What I propose is that the items in threads/timelines/notifications should have these and when the user initiates an action on them, they should return to a url that jumps right back to the item.
This could also be used for getting rid of confirmations for boosts and faves completely, by just doing the fave and loading the page again, but with the address of the source item.

**Comment by jfmcbrayer** [comment]
The first part is doable; probably useful for the reply page, too. Will work better once I can implement absolute paging (waiting on a Mastodon.py feature).

It's not enough for getting rid of confirmations for boosts and faves, because those have to be POSTs, but the links are GETs.
