### ISSUE TITLE
Redraft breaks mentions

### ISSUE THREAD

**Issue by raingloom** [jfmcbrayer/brutaldon#53]
When mentioning `@user@example.com` and then redrafting the post, it only fills in `@user`, which is very easy to miss and a hassle to hand-edit.

Not sure what the best way to fix it is, I know there is some support for detecting what a link is, like when you enter a post's or a user's URL into the search, it shows the correct data within the app. Couldn't that be used to recover which links are mentions and who they mention?

**Comment by jfmcbrayer** [comment]
This is fixed, basically. It should include all of the fixed mentions, though in tough enough cases (`@gcupc` at a bunch of different instances all mentioned, e.g.), they could be out of order, and the spacing could be different from the original.
