### ISSUE TITLE
Show favorite and boost counts

### ISSUE THREAD

**Issue by alexbuzzbee** [jfmcbrayer/brutaldon#61]
Mastodon FE shows the boost and favorite counts of toots when expanded. As far as I can tell, Brutaldon does not do this.

**Comment by jfmcbrayer** [comment]
This is intentional. brutaldon also does not show follower counts. It is part of a design decision to deemphasize quantitative measures of engagement and discourage Clout-seeking.

If you really need to see the numbers, you can click on the posting time to see the post on its home server.
