### ISSUE TITLE
Support Mastodon 2.8 polls

### ISSUE THREAD

**Issue by alexbuzzbee** [jfmcbrayer/brutaldon#62]
In version 2.8, Mastodon added a polls system, similar to Twitter's, that allows users to provide up to four poll options that can be selected. The poll then shows the current results to the original poster, and to any user who has already voted, and the poll ends after a selected period of time, which can range from 5 minutes to 7 days.

Implementation will probably take some time, but it would be nice to have.

Unfortunately, this creates a namespace collision with the polling mechanisms Brutaldon uses to retrieve real-time-ish data.

Apologies if I've missed an existing issue along these lines.

**Comment by jfmcbrayer** [comment]
This would take API support in https://github.com/halcy/Mastodon.py, which I don't have commit access to. I will open an issue for it there, and *may* eventually start a pull request for it, but possibly not for a while.

**Comment by jfmcbrayer** [comment]
Brutaldon now supports viewing and voting in polls. I'm going to close the issue now; I'm still pondering how to implement the UI for creating polls without wrecking the posting UI generally.
