### ISSUE TITLE
Search seems to be broken?

### ISSUE THREAD

**Issue by raingloom** [jfmcbrayer/brutaldon#63]
post itself: https://elekk.xyz/@noelle/102052069436957820

search: https://brutaldon.online/search_results?q=https%3A%2F%2Felekk.xyz%2F%40noelle%2F102052069436957820

returns 500 error

**Comment by raingloom** [comment]
(searching it in the Mastodon web app works)

**Comment by jfmcbrayer** [comment]
It's probably something I messed up while updating paging. Will look at it soon.

**Comment by jfmcbrayer** [comment]
This appears to be caused by updating Mastodon.py: https://github.com/halcy/Mastodon.py/issues/167

**Comment by jfmcbrayer** [comment]
This has been fixed upstream.
